""" Migration"""
# Generated by Django 3.2 on 2021-11-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration"""

    initial = True

    dependencies = [
        ("core_main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("xml_content", models.TextField()),
                ("template_info", models.JSONField(default=dict)),
                (
                    "permission_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("detail_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "access_data_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "last_modification_date",
                    models.DateTimeField(blank=True, default=None),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True, null=True)),
                ("data_sources", models.JSONField(blank=True, default=list)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "templates",
                    models.ManyToManyField(
                        blank=True, default=[], to="core_main_app.Template"
                    ),
                ),
            ],
            options={
                "verbose_name": "Query",
                "verbose_name_plural": "Queries",
            },
        ),
    ]
